### PR TITLE
Update ember-template-lint to 0.7.2

### LINKED ISSUE #262: Contextual components trigger 'not a valid name for a helper'
A template like this (from http://www.ember-bootstrap.com/api/classes/Components.Dropdown.html):
```
{#bs-dropdown as |dd|}}
  {{#dd.toggle}}Dropdown <span class="caret"></span>{{/dd.toggle}}
  {{#dd.menu as |ddm|}}
    {{#ddm.item}}
      {{#ddm.link-to "index"}}Something{{/ddm.link-to}}
    {{/ddm.item}}
    {{ddm.divider}}
    {{#ddm.item}}
      {{#ddm.link-to "index"}}Something different{{/ddm.link-to}}
    {{/ddm.item}}
  {{/dd.menu}}
{{/bs-dropdown}}
```

causes 
```
undefined: `dd.toggle` is not a valid name for a helper on line 3. (project/components/my-component/template): 
    `Error: `dd.toggle` is not a valid name for a helper on line 3.
```

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #262

### CODE REVIEW

**Comment by simonihmig** [comment]
@rwjblue would love a release of ember-cli-template-lint as well, so we get the upstream fix here https://github.com/rwjblue/ember-template-lint/pull/241. Thanks! :)

**Comment by rwjblue** [comment]
It's a floating dep, a release is not needed for your projects to obtain the fix.

**Comment by rwjblue** [comment]
Generally a  `yarn upgrade` should do the trick.

**Comment by simonihmig** [comment]
You are right of course, was too early in the morning... ;)

Does the PR still make sense to you, or should I close it?

**Comment by rwjblue** [comment]
Ya, definitely seems good to bump the minimum version. I just won't be able to release for a few hours and didn't want you to be stuck waiting. 😃

**Pull request merged**
