### PR TITLE
[WIP] Add rule: extra-white-lines

### LINKED ISSUE #38: Rule: Disallow extraneous white lines.
``` hbs
<h1>Foo</h1>


<ul>
  <li>something</li>
  <li>interesting</li>
</ul>
```

Should warn about an extra white line on line 3.

### PR DESCRIPTION
**Pull request by martndemus**
Closes #38.
Spiked this out, but not really having luck on retrieving the location information.

### CODE REVIEW

**Comment by rwjblue** [comment]
In general, the technique seems to work: http://jsbin.com/wusaget/edit?html,js,output

**Comment by rwjblue** [comment]
@martndemus - Any progress on this, did the JSBin help?

**Comment by rwjblue** [comment]
@martndemus - Ping?

**Comment by martndemus** [comment]
@rwjblue Getting the file the error is detected works, but `TextNode`s don't have line infos.

**Comment by martndemus** [comment]
@rwjblue Found something to find out the line numbers. But still figuring out what is an error and what not. Feedback is welcome.

**Comment by martndemus** [comment]
E.g.: 

Is a block with an empty line an error?
```hbs
{{#x-foo}}

{{/x-foo}}
```

Is leading/trailing white lines in a block and error?
```hbs
{{#x-foo}}

  <input />
{{/x-foo}}
```

**Comment by rwjblue** [comment]
TextNodes not having loc info is a known issue, we will have to fix it upstream (if someone else doesn't get to it soon I'll tackle it).

**Comment by martndemus** [comment]
@rwjblue I reverted it back to how it was originally. Although I have added a few more test cases.
It looks like within handlebars blocks the first newline get clobbered from the text node.

**Comment by rwjblue** [comment]
I'm going to close this for now, please let me know if you want to pick it back up...

**Comment by rwjblue** [comment]
@martndemus - @fivetanely and I fixed `TextNode`s to now have location info.  I think this may make it easier to implement this rule...

**Comment by martndemus** [comment]
Awesome! 👍

**Pull request closed without merging**
