### PR TITLE
Add ability to disable all rules or a subset of rules.

### LINKED ISSUE #17: Add general file level comment to disable in template.
Should allow ignoring a specific rule or all rules (ala `// jscs disable`)...

### PR DESCRIPTION
**Pull request by rwjblue**
Syntax is:

```hbs
<!-- template-lint disable=true -->

{{! do bad things ;P }}
```

```hbs
<!-- template-lint triple-curlies=false -->

{{{foo}}}
```

Closes #17.

### CODE REVIEW

**Comment by mixonic** [comment]
@rwjblue it is bikeshedding a bit, what what do you think of using a comment as with JS linters?

```hbs
{{! template-lint triple-curlies=false }}
<div>{{{foo}}}</div>
```

**Comment by rwjblue** [comment]
Comments are stripped completely and we loose access from the AST plugin (I tried that first).

**Comment by rwjblue** [comment]
OK, so I was correct `{{! foo }}` is stripped in Handlebars parsing (and is never included in the actual AST), but I didn't check HTML comments which do appear as `CommentStatement`'s.

That would end up looking like:

```html
    <!-- template-lint disabled=true -->
    <!-- template-lint triple-curlies=false -->
```

Demo here: http://rwjblue.jsbin.com/jibakaj/edit?html,output.

@mixonic - Would you prefer this?

**Comment by rwjblue** [comment]
Just let me know, I can update this PR to do that instead...

**Comment by mixonic** [comment]
IMO `<!-- template-lint disabled=true -->` is better than a mustache invocation. Mustache invocation is already mildly confusing (is this a helper or component), and adding a new odd type would be unfortunate IMO.

**Comment by rwjblue** [comment]
Sounds good, I'll update...

**Comment by rwjblue** [comment]
Updated from `{{! template-lint foo-bar=false }}` to `<!-- template-lint foo-bar=false -->` style.

@mixonic - Ready for another review...

**Pull request merged**
