### PR TITLE
Add rule lint-quotes (DON'T MERGE)

### PR DESCRIPTION
**Pull request by oriSomething**
#### config:
- `false` - disable
- `true` - only require qoutes for HTML attributes 
- `"single"` - always single quotes
- `"double"` - always double quotes
- `["single", "avoidEscape"]` - prefer single quotes unless there is an escape needed only to single quotes
- `["double", "avoidEscape"]` - prefer double quotes unless there is an escape needed only to double quotes

#### todos: 
- [x] adding support for HTML attributes
- [ ] adding support for HTMLBars helper attributes
- [x] adding support for only requiring qoutes
- [ ] adding README / and to blueprints
- [ ] adding avoidEscape supports
- [ ] adding avoidEscape to README

if i miss something, please tell me

### CODE REVIEW

**Comment by rwjblue** [comment]
I am very confused ;P, I don't see any changes....

**Comment by oriSomething** [comment]
😄  yep, it's a todo list for me that i'm working accordingly because it's more complicated rule than what i've used to. you must have an empty commit for open a PR ;-)
anyway, i'm on it

**Comment by rwjblue** [comment]
AHA! I see, ok. Thought Github was playing tricks on me 😝

**Comment by rwjblue** [comment]
I'm still working on some refactors so it may be a bit painful rebase wise but you may want to target https://github.com/rwjblue/ember-template-lint instead of this repo.

**Comment by oriSomething** [comment]
thanks… i'll start here and than when it'll ready i'l open PR there and close here

**Comment by oriSomething** [comment]
another thing that i've realized after starting working on this rule. that maybe we should need a rule to force quotes on HTML attributes. or making this rule also forcing quotes.
example (bad):
```html
<img alt=tomster src=tomster.jpg>
```

**Comment by rwjblue** [comment]
Yes, I agree we should require quotes there.

**Comment by rwjblue** [comment]
OK, this will need to be moved over to https://github.com/rwjblue/ember-template-lint now.  The structure and whatnot is very similar, hopefully it is straightforward to port.

I'll leave this PR open, please close when you open the other one.

**Comment by rwjblue** [comment]
How's it going on this?

**Comment by oriSomething** [comment]
just have busy time so didn't work on it. i hope this weekend i'll return (and finish it)

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/rwjblue/ember-template-lint/pull/42

**Pull request closed without merging**
