### PR TITLE
Implement html-comments rule

### LINKED ISSUE #64: Rule: Disallow HTML comments
I can't think of a good use case for using ```<!-- HTML comments -->``` in templates since ```{{!-- handlebars comments --}}``` serve the purpose of commenting the template, but are not included in the compiled output and eventual DOM. But I'm so used to HTML comments that I always forget and use them when I don't mean to! I'd love a lint rule to catch this.

I see that the linter uses HTML comments for its instructions. Is this because brocolli-template-lint doesn't expose handlebars comments or something? Or could it instead support instructions in handlebars comments? I believe this rule could be made to work either way (obviously ignoring HTML comments that are instructions to the linter).

I'd be happy to take a crack at a PR for this if it sounds like a good idea outside of my head as well as inside of it :smile:

### PR DESCRIPTION
**Pull request by bendemboski**
Forbid HTML comments in favor of Handlebars comments (fixes #64)

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks good! Can you mention that the HTML comment to disable rules does not trigger an error in the README?

**Comment by bendemboski** [comment]
Ah, good idea -- updated.

**Comment by rwjblue** [comment]
Thank you!

**Comment by rwjblue** [comment]
Released as v0.3.1.

**Pull request merged**
